# Configuration of NH Planner
planner_name: NHPlanner
k_ancestors: 1

#Corner parameters
k: 3
ray: 0.3
threshold: 0.40
discretization: 360
corner_step: 0.1

#los parameters
step: 0.05
micro: 0.1
macro: 0.3
k_los: 2


#Samplers parameters
#options: Gaussian2D, LineGaussian, Fixed, Uniform2D
position_sampler: Gaussian2D
#options: Fixed, Beta, BernoulliExponential, Atan
angle_sampler: Beta


# notEpsilonh
epsilon: 0.3
