# Configuration of NH Planner
planner_name: NHPlanner
k_ancestors: 1000

#Corner parameters
k: 3
ray: 1.0
threshold: 0.40
discretization: 360
corner_step: 0.5

#los parameters
step: 0.5
micro: 1.0
macro: 1.5


#Samplers parameters
#options: Gaussian2D, LineGaussian, Fixed, Uniform2D
position_sampler: Gaussian2D
#options: Fixed, Beta, BernoulliExponential, Atan
angle_sampler: Beta
