# Configuration for differential drive kinematic planning
extender: MotionPrimitives
kinematicModel: DifferentialDrive
motion_primitives:
  minU: [0, -0.78539816339]
  maxU: [1, 0.78539816339]
  discretization: 20
